# Generated by Django 4.1.6 on 2023-02-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('match_alias', models.CharField(max_length=45)),
                ('date_played', models.DateTimeField()),
                ('game_version_id', models.IntegerField()),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='MatchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
                ('second_role', models.IntegerField()),
                ('modifier_id', models.IntegerField()),
                ('death_id', models.IntegerField()),
                ('killed_by', models.IntegerField()),
                ('killed_by_role', models.IntegerField()),
                ('did_win', models.BooleanField()),
            ],
            options={
                'db_table': 'match_results',
            },
        ),
    ]
